version: '3.3'

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./.docker/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
