version: '3.3'

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: ''
        volumes:
            - ./.docker/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306

    redis:
        image: redis:6
        command: redis-server
        ports:
            - 6379:6379
