version: '3.3'

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: ''
        volumes:
            - ./.docker/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306

    redis:
        image: redis:6
        command: redis-server
        ports:
            - 6379:6379

    elasticsearch:
        image: elasticsearch:7.17.18
        environment:
            discovery.type: single-node
            xpack.security.enabled: 'false'
        volumes:
            - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    mailer:
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
